### ISSUE TITLE
No getting started in README

### ISSUE THREAD

**Issue by berenddeboer** [yonigibbs/elm-i18next-gen#2]
The README contains a lot of detail why you want to use this package but nothing about how.

It has the part to create the `Translations.elm` but then??

I suppose I have to look somewhere else, but it would be good to have that listed first, and the technical details later.

**Comment by berenddeboer** [comment]
For example I saw you need to install elm-i18next as well. Which is sort of hinted at, and clear when you read the generated code. But I would simply put the full recipe in the README.

**Comment by yonigibbs** [comment]
Hey @berenddeboer.  Thanks for logging an issue!  I totally agree with your suggestion.  I've now added a [Getting Started](https://github.com/yonigibbs/elm-i18next-gen#getting-started) section to the readme, and moved the [Motivation](https://github.com/yonigibbs/elm-i18next-gen#motivation) section a bit lower down.

If you get a chance can you take a look and see if you think it addresses all your concerns? If you're happy with it I'll then close this issue.

@ChristophP: this now includes some instructions about `elm-i18next` itself. Have a look if you're interested and let me know if there's anything there I've missed or you think could be explained better.

Thanks both!

**Comment by ChristophP** [comment]
@yonigibbs Yeah, looks good and I think it makes getting started a bit easier for newbies. I would make mention in point `3.` that you'll most likely fetch the json from somewhere or make the code snippet there look like this:
```js
const translations = await fetch('/path/to/files/translations.en.json');
Elm.Main.init({ flags: translations });
```
Of course you could do the fetching from within Elm as well.
Other than that, it looks pretty good.

**Comment by yonigibbs** [comment]
Agreed, thanks @ChristophP. Have updated the readme accordingly.

**Comment by ChristophP** [comment]
Great :+1:

**Comment by berenddeboer** [comment]
Another problem I had is: where do I get my initial language from?? I ended up with this:

```javascript
var language = window.navigator.userLanguage || window.navigator.language || "en"language = language.replace(/\-.+$/, '')
var json = require('/' + language + '.json')
const flags = json
```

Probably `await fetch` is better, but I was using `loadjs` already.

**Comment by berenddeboer** [comment]
I agree the README is much better now, much more like a recipe! Ticket can be closed.

The discussion around Accept-Language is possibly not helpful for Elm SPAs, I don't have a server, just an S3 bucket. So that's why I did what I had above.

**Comment by yonigibbs** [comment]
Cool, thanks @berenddeboer , glad the changes have helped clarify things. Good luck figuring out how to get the JSON: it really depends on your setup, I guess.  (And good luck deciding whether to use this or https://github.com/layflags/elm-translation :-))  It looks like a great package.  Definitely worth investigating both options and seeing which works better for you.
