### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by MikeTschudi** [yonigibbs/elm-i18next-gen#4]
Please consider adding a license to this work. I would very much like to use it at work, but cannot without an [Apache-compatible license](https://www.apache.org/legal/resolved.html#category-a). Thank you.

**Comment by yonigibbs** [comment]
Hey @MikeTschudi, thanks for reaching out. That's great you want to use this. Hope it's of use to you (we're using it at work too and finding it useful). No problem to add a license. Leave it with me and I'll get it done ASAP.

And don't hesitate to log issues or ping me on the Elm slack if you have any questions/problems/suggestions.

Cheers!

**Comment by yonigibbs** [comment]
Have added an MIT license file. Let me know if there's anything else that needs to be done to make it OK for you to use this at work. Or just close this issue if that's sufficient.

Thanks!

**Comment by MikeTschudi** [comment]
@yonigibbs, thank you very much!
